[theme]

# Primary accent for interactive elements
primaryColor = '#1db954'

# Background color for the main content area
backgroundColor = '#fafafa'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#f0f2f6'

# Color used for almost all text
textColor = '#161513'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"